const knownDomains = {
  "ouo.io": "OUO",
  "ouo.press": "OUO",
  "linkvertise.com": "Linkvertise",
  "link-target.net": "Linkvertise",
  "link-center.net": "Linkvertise",
  "link-hub.net": "Linkvertise",
  "direct-link.net": "Linkvertise",
  "zovo.ink": "PhpShortener",
  "go.zovo.ink": "PhpShortener",
  "vuotlink.xyz": "PhpShortener",
  "oklink2.online": "PhpShortener",
  "terabox.com": "Terabox",
  "dm.terabox.com": "Terabox",
  "terabox.app": "Terabox",
  "1024terabox.com": "Terabox",
  "4funbox.com": "Terabox",
  "shrinkme.io": "ShrinkMe",
  "shrinkme.click": "ShrinkMe",
  "shrinke.me": "ShrinkMe",
  "shorte.st": "Shorte.st",
  "sh.st": "Shorte.st",
  "adf.ly": "Adf.ly",
  "bc.vc": "BCVC",
  "exe.io": "Exe.io",
  "tei.ai": "TEI",
  "cuturl.cc": "CutURL",
  "linksfly.com": "LinksFly",
  "gplinks.com": "GPLinks",
  "gplink.co": "GPLinks",
  "gplink.net": "GPLinks",
  "mitly.us": "Mitly",
  "cutp.in": "CutP",
  "fc.lc": "FC.LC",
  "za.gl": "ZA.GL",
  "tnlink.in": "TNLink",
  "link1s.com": "Link1S",
  "linkspy.cc": "LinkSpy",
  "cutdy.link": "Cutdy",
  "safelinku.com": "SafelinkU",
  "safelinku.net": "SafelinkU",
  "sfl.gl": "Safelinku",
  "sfl.link": "Safelinku",
  "app.khaddavi.net": "Khaddavi",
  "khaddavi.net": "Khaddavi",
  "dutchycorp.com": "DutchyCorp",
  "tpi.li": "TPI",
  "tpi.ac": "TPI",
  "srtam.com": "TPI",
  "oii.la": "TPI",
  "clksz.com": "TPI",
  "clk.sh": "TPI",
  "srnky.com": "TPI",
  "bit.ly": "Bit.ly",
  "tinyurl.com": "TinyURL",
  "t.co": "Twitter",
  "is.gd": "is.gd",
  "v.gd": "v.gd",
  "rb.gy": "rb.gy",
  "rebrand.ly": "Rebrandly",
  "buff.ly": "Buffer",
  "shorturl.at": "ShortURL",
  "dl-protect.com": "DL-Protect",
  "ouo.io/go": "OUO",
  "linkvertise.com/api": "Linkvertise",
};

function identifyShortener(url) {
  try {
    const host = new URL(url).hostname.replace("www.", "");
    return knownDomains[host] || null;
  } catch {
    return null;
  }
}

module.exports = { knownDomains, identifyShortener };
